### ISSUE TITLE
Mods not working

### ISSUE THREAD

**Issue by infyrno1010101** [Acekorneya/Ark-Survival-Ascended-Server#12]
Idk if im doing something wrong but when I add the mod id, to the docker compose file and do docker compose up -d. I load the game then search for my server it always says the mods are set to no.

services:
  asaserver:
    build: .
    image: acekorneya/asa_server:latest
    container_name: asa_ace
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - RCON_ENABLED=TRUE                     #Needed for Graceful Shutdown
      - DISPLAY_POK_MONITOR_MESSAGE=TRUE      # Or FALSE to suppress the Server Monitor
      - MAP_NAME=TheIsland
      - SESSION_NAME=Sedufun
      - SERVER_ADMIN_PASSWORD=<blank>
      - ASA_PORT=7777
      - RCON_PORT=27015
      - MAX_PLAYERS=20
      - CLUSTER_ID=cluster0673625
      - CUSTOM_SERVER_ARGS=                   #If You need to add more Custom Args -ForceRespawnDinos -ForceAllowCaveFlyers
      - BATTLEEYE=FALSE                       # Set to TRUE to use BattleEye, FALSE to not use BattleEye
      - MOD_IDS=936278,929420                        # Add your mod IDs here, separated by commas, e.g., 123456789,987654321
is anyone else experiencing the same issue?

**Comment by Acekorneya** [comment]
I have tried it myself with the mod ID you are using and is working correctly 

![Screenshot 2023-11-22 093816](https://github.com/Acekorneya/Ark-Survival-Ascended-Server/assets/132539744/7b0eb827-d406-4cd7-8a05-84e9b62ff3d2)
![Screenshot 2023-11-22 093808](https://github.com/Acekorneya/Ark-Survival-Ascended-Server/assets/132539744/cbebe2cd-3116-4c31-bae4-c61861a46fa7)

```
version: '2.4'

services:
  asaserver:
    build: .
    image: acekorneya/asa_server:latest
    container_name: asa_Server
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - BATTLEEYE=FALSE
      - RCON_ENABLED=TRUE  
      - DISPLAY_POK_MONITOR_MESSAGE=TRUE
      - MAP_NAME=TheIsland
      - SESSION_NAME=POK TESTING SERVER
      - SERVER_ADMIN_PASSWORD=
      - ASA_PORT=8777
      - RCON_PORT=27020
      - MAX_PLAYERS=70
      - CLUSTER_ID=kny
      - MOD_IDS=936278,929420
      - CUSTOM_SERVER_ARGS=
    ports:
      - "8777:8777/tcp"
      - "8777:8777/udp"
    volumes:
      - "./ASA:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame"
      - "./ARK Survival Ascended Dedicated Server:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server"
      - "./Cluster:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ShooterGame"
```
