### ISSUE TITLE
Container exits after restart

### ISSUE THREAD

**Issue by rediculum** [Acekorneya/Ark-Survival-Ascended-Server#13]
Has anyone an idea, why this happens when I stop and then start the container?
```
# docker-compose logs -f asa
asa  | usermod: no changes
asa  | No update required. Server build ID 12835038 is up to date.
asa  | Server is already running the latest build ID 12835038. Proceeding to start the server.
asa  | Using map: TheIsland_WP
asa  | Cluster directory already exists. Skipping folder creation.
asa  | Server process started with PID: 58
asa  | PID 58 written to /usr/games/ark_server.pid
asa  | No updates.
asa  | ARK server process (PID: 58) is running.
asa  | Log file not found after waiting. Please check server status.
asa exited with code 0
```
When I delete content of the persistent volume and then start the container, it works again (of course with all data lost)

**Comment by Acekorneya** [comment]
it could be something in you docker-compose.yaml is not configure correctly that maybe is causing that...

**Comment by rediculum** [comment]
I don't see any problem in my compose file:
```
  asa:
    image: acekorneya/asa_server:latest
    container_name: asa
    restart: unless-stopped
    environment:
      - TZ=Europe/Zurich
      - PUID=1001
      - PGID=1001
      - BATTLEEYE=FALSE
      - RCON_ENABLED=FALSE
      - DISPLAY_POK_MONITOR_MESSAGE=TRUE
      - UPDATE_SERVER=TRUE
      - CHECK_FOR_UPDATE_INTERVAL=24
      - RESTART_NOTICE_MINUTES=30
      - MAP_NAME=TheIsland_WP
      - SESSION_NAME=(SUI) ReDi's Docker Server
      - SERVER_ADMIN_PASSWORD=*****
      - ASA_PORT=7779
      - RCON_PORT=27020
      - MAX_PLAYERS=15
      - CLUSTER_ID=cluster
      - MOD_IDS="929110,930392,900062,927131,928988,914844,912902,926956,916922,908148,930115,928621" # Add your mod IDs here, separated by commas, e.g., 123456789,987654321
      - CUSTOM_SERVER_ARGS=""
    volumes:
      - asa_data:/usr/games/.wine/drive_c/POK
    ports:
      - 7779:7779/tcp
      - 7779:7779/udp
      - 27017:27017/udp
      - 27020:27020
```
I have to correct: There's no need to wipe the persistent volume. I just need to stop and remove the container and recreate it and then the server starts. The message with the missing log file does not appear then.

**Comment by Acekorneya** [comment]
so what is the main issue then... normally you do docker compose down it will kill the container but you folder with the data should be intact and when you do docker compose up it will rebuild the container but everything should still work and nothing delete...

**Comment by Acekorneya** [comment]
> I don't see any problem in my compose file:
> 
> ```
>   asa:
>     image: acekorneya/asa_server:latest
>     container_name: asa
>     restart: unless-stopped
>     environment:
>       - TZ=Europe/Zurich
>       - PUID=1001
>       - PGID=1001
>       - BATTLEEYE=FALSE
>       - RCON_ENABLED=FALSE
>       - DISPLAY_POK_MONITOR_MESSAGE=TRUE
>       - UPDATE_SERVER=TRUE
>       - CHECK_FOR_UPDATE_INTERVAL=24
>       - RESTART_NOTICE_MINUTES=30
>       - MAP_NAME=TheIsland_WP
>       - SESSION_NAME=(SUI) ReDi's Docker Server
>       - SERVER_ADMIN_PASSWORD=*****
>       - ASA_PORT=7779
>       - RCON_PORT=27020
>       - MAX_PLAYERS=15
>       - CLUSTER_ID=cluster
>       - MOD_IDS="929110,930392,900062,927131,928988,914844,912902,926956,916922,908148,930115,928621" # Add your mod IDs here, separated by commas, e.g., 123456789,987654321
>       - CUSTOM_SERVER_ARGS=""
>     volumes:
>       - asa_data:/usr/games/.wine/drive_c/POK
>     ports:
>       - 7779:7779/tcp
>       - 7779:7779/udp
>       - 27017:27017/udp
>       - 27020:27020
> ```
> 
> I have to correct: There's no need to wipe the persistent volume. I just need to stop and remove the container and recreate it and then the server starts. The message with the missing log file does not appear then.

i see you issue you docker-compose.yaml is incorrect that is why the volumes are not working you need to keep the volumes they way i have them set up if not the whole container breaks... so i fixed you docker compose.yaml file please only change the environment variable... below is the correct docker-compose.yaml file 
```
 asa:
    image: acekorneya/asa_server:latest
    container_name: asa
    restart: unless-stopped
    environment:
      - TZ=Europe/Zurich
      - PUID=1001
      - PGID=1001
      - BATTLEEYE=FALSE
      - RCON_ENABLED=FALSE
      - DISPLAY_POK_MONITOR_MESSAGE=TRUE
      - UPDATE_SERVER=TRUE
      - CHECK_FOR_UPDATE_INTERVAL=24
      - RESTART_NOTICE_MINUTES=30
      - MAP_NAME=TheIsland
      - SESSION_NAME=(SUI) ReDi's Docker Server
      - SERVER_ADMIN_PASSWORD=*****
      - ASA_PORT=7779
      - RCON_PORT=27020
      - MAX_PLAYERS=15
      - CLUSTER_ID=cluster
      - MOD_IDS="929110,930392,900062,927131,928988,914844,912902,926956,916922,908148,930115,928621" # Add your mod IDs here, separated by commas, e.g., 123456789,987654321
      - CUSTOM_SERVER_ARGS=""
    volumes:
      - "./ASA:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame"
      - "./ARK Survival Ascended Dedicated Server:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server"
      - "./Cluster:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ShooterGame"
    ports:
      - 7779:7779/tcp
      - 7779:7779/udp
      - 27017:27017/udp
      - 27020:27020
   ```
