### ISSUE TITLE
Cluster folder wiping on reboots

### ISSUE THREAD

**Issue by vertyco** [Acekorneya/Ark-Survival-Ascended-Server#20]
When re-pulling the image and restarting the container via docker compose, the cluster folder gets wiped.
Additionally, when i upload items to the obelisk, even searching the folders when connected to the container i cannot see where they go, they are not in the cluster folder and i could not find them anywhere else.

I have no issue with the other folders, i'm able to configure the `game.ini` and `GameUserSettings.ini` files just fine and they do not get affected by this. however the cluster folder gets entirely wiped each restart.

Here is my `docker-compose.yaml` file:

```
version: '2.4'

services:
  asaserver:
    build: .
    image: acekorneya/asa_server:latest
    container_name: asa_island_pvp
    restart: unless-stopped
    environment:
      - PUID=1000             
      - PGID=1000           
      - BATTLEEYE=TRUE
      - RCON_ENABLED=TRUE
      - DISPLAY_POK_MONITOR_MESSAGE=TRUE
      - MAP_NAME=TheIsland
      - SESSION_NAME=Vertyco PvP (Slightly Boosted)
      - SERVER_ADMIN_PASSWORD=placeholder
      - ASA_PORT=7787
      - RCON_PORT=27040
      - MAX_PLAYERS=100
      - CLUSTER_ID=pvpcluster
      - UPDATE_SERVER=TRUE
      - CHECK_FOR_UPDATE_INTERVAL=24
      - RESTART_NOTICE_MINUTES=30
      - MOD_IDS=
      - CUSTOM_SERVER_ARGS=-ServerRCONOutputTribeLogs -NoTransferFromFiltering
      - ENABLE_MOTD=TRUE
      - MOTD=<RichColor Color="0,1,0,1">Servers running since November 29, 2023</>\n<RichColor Color="1,0,1,1">Exp x4 - Weight x3.5 - Gather x3 - Taming x7.5 - Breeding 90x</>\n\n<RichColor Color="1,0.65,0,1">Join the Discord for events and shop</>\n<RichColor Color="1,0,0,1">discord.gg/</><RichColor Color="0,1,0,1">vertyco</>
      - MOTD_DURATION=60
    ports:
      - "7787:7787/tcp"
      - "7787:7787/udp"
      - "27040:27040/tcp"
    volumes:
      - "/home/vert/pvp/game:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame"
      - "/home/vert/pvp/server:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server"
      - "/home/vert/pvp/cluster:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ShooterGame"
    mem_limit: 16G 
```

Am i just doing something wrong?

Extra Context
- I set the PUID and PGID to the user i sign in with "vert"
- I've already created the folders used in the volume bindings and confirmed that they are working when i place test files in them and then connect to the container to check.
- I'm running it on a VM in proxmox, so the cpu type is set to "Host" as instructed
- I'm running the docker-compose.yaml file from portainer
