### ISSUE TITLE
Server dont start

### ISSUE THREAD

**Issue by cutec-chris** [Acekorneya/Ark-Survival-Ascended-Server#30]
Would be nice if someone can show me what iam doing wrong.
The directory permissions should be ok, UID/GID fits.
But the update/download of ASA dont work (directorys stays clean after starts)

```
  Attaching to asa_Server
  asa_Server   | New server installation or update required...
  asa_Server   | Current build ID is 13278428, initiating installation/update...
  asa_Server   | 0024:err:environ:run_wineboot boot event wait timed out
  asa_Server   | wine: could not load kernel32.dll, status c0000135
  asa_Server   | 002c:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
  asa_Server   | cp: cannot stat '/usr/games/.wine/drive_c/POK/Steam/steamapps/appmanifest_2430930.acf': No such file or directory
  asa_Server   | Installation or update completed successfully.
  asa_Server   | Server update detected...
  asa_Server   | Updating server to build ID 13278428 from ...
  asa_Server   | 004c:err:environ:run_wineboot boot event wait timed out
  asa_Server   | wine: could not load kernel32.dll, status c0000135
  asa_Server   | 0054:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
  asa_Server   | cp: cannot stat '/usr/games/.wine/drive_c/POK/Steam/steamapps/appmanifest_2430930.acf': No such file or directory
  asa_Server   | Server update completed successfully.
  asa_Server   | Cluster directory already exists. Skipping folder creation.
  asa_Server   | 005c:fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
  asa_Server   | Server process started with PID: 86
  asa_Server   | PID 86 written to /usr/games/ark_server.pid
  asa_Server   | 0054:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
  asa_Server   | 0054:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
  asa_Server   | 0054:err:systray:initialize_systray Could not create tray window
  asa_Server   | 0054:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x80004002
  asa_Server   | 0054:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x80004002
  asa_Server   | 0054:err:ole:apartment_get_local_server_stream Failed: 0x80004002
  asa_Server   | 002c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
  asa_Server   | 002c:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
  asa_Server   | 005c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
  asa_Server   | 005c:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
  asa_Server   | 005c:err:ole:apartment_createwindowifneeded CreateWindow failed with error 3
  asa_Server   | 005c:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
  asa_Server   | 005c:err:ole:apartment_createwindowifneeded CreateWindow failed with error 14007
  asa_Server   | 005c:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hr 0x800736b7
  asa_Server   | 005c:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, hr 0x800736b7
  asa_Server   | 005c:err:ole:apartment_get_local_server_stream Failed: 0x800736b7
  asa_Server   | 005c:err:ole:start_rpcss Failed to open RpcSs service
  asa_Server   | 0044:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
  asa_Server   | 0044:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
  asa_Server   | 00a4:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
  asa_Server   | 00a4:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
  asa_Server   | 00ac:fixme:file:NtLockFile I/O completion on lock not implemented yet
  asa_Server   | 00ac:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
  asa_Server   | 00b4:fixme:file:NtLockFile I/O completion on lock not implemented yet
  asa_Server   | 00b4:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
  asa_Server   | 00b4:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
  asa_Server   | 00b4:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
  asa_Server   | 00ac:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
  asa_Server   | 00ac:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
  asa_Server   | 011c:fixme:msg:pack_message msg 14 (WM_ERASEBKGND) not supported yet
  asa_Server   | 011c:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
  asa_Server   | 011c:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
  asa_Server   | 0144:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
  asa_Server   | 0144:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
  asa_Server   | 0144:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
  asa_Server   | 0144:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
  asa_Server   | wine: configuration in L"/usr/games/.wine" has been updated.
  asa_Server   | 2024/01/28 10:02:27 Failed to connect to RCON serverdial tcp 127.0.0.1:27020: connect: connection refused
  asa_Server   | Log file not found after waiting. Please check server status.
```

**Comment by Acekorneya** [comment]
are you running this under a root user?? the reason im asking is because it seems like your having permissions issues that wont let wine start up

**Comment by cutec-chris** [comment]
i run this in docker and docker daemon runs always as root, am i wrong ?
90% of the messages are from wine or not ?

**Comment by cutec-chris** [comment]
ive tried the same now without mounted volumes, with same result so cant be volume permission issue

**Comment by Acekorneya** [comment]
can you maybe post your docker-compose.yaml file and can you also try it again but make sure to get the latest docker image by doing docker pull acekorneya/asa_server:latest and then doing sudo docker compose up

**Comment by cutec-chris** [comment]
thats the compose:
```
version: '2.4'

services:
  asaserver:
    build: .
    image: acekorneya/asa_server:latest
    container_name: asa_Server
    restart: unless-stopped
    environment:
      - PUID=1000                            # The UID to run server as
      - PGID=1000                            # The GID to run server as
      - BATTLEEYE=FALSE                      # Set to TRUE to use BattleEye, FALSE to not use BattleEye
      - RCON_ENABLED=TRUE                    # Needed for Graceful Shutdown / Updates / Server Notifications
      - DISPLAY_POK_MONITOR_MESSAGE=FALSE    # Or TRUE to Show the Server Monitor Messages / Update Monitor 
      - UPDATE_SERVER=TRUE                   # Enable or disable update checks
      - CHECK_FOR_UPDATE_INTERVAL=24         # Check for Updates interval in hours
      - UPDATE_WINDOW_MINIMUM_TIME=12:00 AM  # Defines the minimum time, relative to server time, when an update check should run
      - UPDATE_WINDOW_MAXIMUM_TIME=11:59 PM  # Defines the maximum time, relative to server time, when an update 
      - RESTART_NOTICE_MINUTES=30            # Duration in minutes for notifying players before a server restart due to updates
      - ENABLE_MOTD=FALSE                    # Enable or disable Message of the Day
      - MOTD=                                # Message of the Day
      - MOTD_DURATION=30                     # Duration for the Message of the Day
      - MAP_NAME=TheIsland
      - SESSION_NAME=Server_name
      - SERVER_ADMIN_PASSWORD=MyPassword
      - SERVER_PASSWORD=                     # Set a server password or leave it blank (ONLY NUMBERS AND CHARACTERS ARE ALLOWED BY DEVS)
      - ASA_PORT=7777
      - RCON_PORT=27020
      - MAX_PLAYERS=70
      - CLUSTER_ID=cluster
      - MOD_IDS=                             # Add your mod IDs here, separated by commas, e.g., 123456789,987654321
      - PASSIVE_MODS=                        # Replace with your passive mods IDs
      - CUSTOM_SERVER_ARGS=                  # If You need to add more Custom Args -ForceRespawnDinos -ForceAllowCaveFlyers
    ports:
      - "7777:7777/tcp"
      - "7777:7777/udp"
    #volumes:
    #  - "./ASA:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame"
    #  - "./ARK Survival Ascended Dedicated Server:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server"
    #  - "./Cluster:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ShooterGame"
    mem_limit: 16G 
```

uid and gid fits the user
