### ISSUE TITLE
What would the compose file look like for two more servers?

### ISSUE THREAD

**Issue by msuprobo** [Acekorneya/Ark-Survival-Ascended-Server#35]
I want to setup a cluster but am unsure what it would like with two or more servers (i.e. theisland and svartalfheim). Especially in regard to the way the volumes are built out.

**Comment by Acekorneya** [comment]
you just got to make a folder on the host and have all you docker-compose.yaml File look at the same folder in the volumes: here in an example for two server that i have clustered 
docker-compose.yaml #1
```yaml
    volumes:
      - "./ASA:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame"
      - "./ARK Survival Ascended Dedicated Server:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server"
      - "/home/factorioserver/ASA_Cluster/Cluster:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame/Saved/clusters"
    mem_limit: 18G  # Setting memory limit to 12GB
```
Docker-compose.yaml #2
```yaml
    volumes:
      - "./ASA:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame"
      - "./ARK Survival Ascended Dedicated Server:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server"
      - "/home/factorioserver/ASA_Cluster/Cluster:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame/Saved/clusters"
    mem_limit: 18G  # Setting memory limit to 12GB
```
As you can see they both look the same the only differance is the cluster folder both docker-compose.yaml file have the same folder path which is `/home/factorioserver/ASA_Cluster/Cluster` you never want to change this folder ALWAYS keep them how they are `/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame/Saved/clusters`
