### ISSUE TITLE
Updating to version 2.0 causes server to reset

### ISSUE THREAD

**Issue by vertyco** [Acekorneya/Ark-Survival-Ascended-Server#39]
I've been using docker-compose to run the servers for a while (havent used POK-Manager.sh)

I recently changed `acekorneya/asa_server:latest` to `acekorneya/asa_server:2_0_latest` and redeployed and when I did that the server started up at day 1 with everyone's stats reset including the whole map.

Checking the map files they are still there, and reverting back to `acekorneya/asa_server:latest` and redeploying again made things go back to normal...

Changing the container-side volume mounts to the ones in the new docker-compose also fails to start the server entirely, is there an update process we need to follow or something? Any ideas why this would be happening?

Here is my docker-compose for reference:
```
version: '2.4'

services:
  asaserver:
    build: .
    image: acekorneya/asa_server:latest
    container_name: asa_island_pve
    restart: unless-stopped
    environment:
      - PUID=1000               
      - PGID=1000         
      - TZ=America/New_York      
      - BATTLEEYE=TRUE
      - RCON_ENABLED=TRUE
      - DISPLAY_POK_MONITOR_MESSAGE=FALSE
      - MAP_NAME=TheIsland
      - SESSION_NAME=Vertyco PvE (Slightly Boosted)
      - SERVER_ADMIN_PASSWORD=REDACTED
      - ASA_PORT=7797
      - RCON_PORT=27050
      - MAX_PLAYERS=100
      - CLUSTER_ID=pvecluster
      - UPDATE_SERVER=TRUE
      - CHECK_FOR_UPDATE_INTERVAL=24
      - UPDATE_WINDOW_MINIMUM_TIME=12:00 AM
      - UPDATE_WINDOW_MAXIMUM_TIME=11:59 PM
      - RESTART_NOTICE_MINUTES=30
      - MOD_IDS=928988
      - CUSTOM_SERVER_ARGS=-ServerRCONOutputTribeLogs
      - ENABLE_MOTD=TRUE
      - MOTD=<RichColor Color="0,1,0,1">Servers wipe every 3 months (Next wipe January 6th)</>\n<RichColor Color="1,0,1,1">Exp x4 - Weight x3.5 - Gather x3 - Taming x7.5 - Breeding 90x</>\n\n<RichColor Color="1,0.65,0,1">Join the Discord for events and shop</>\n<RichColor Color="1,0,0,1">discord.gg/</><RichColor Color="0,1,0,1">vertyco</>
      - MOTD_DURATION=30
    ports:
      - "7797:7797/tcp"
      - "7797:7797/udp"
      - "27050:27050/tcp"
    volumes:
      - "/home/vert/pve/game:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame"
      - "/home/vert/pve/server:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server"
      - "/home/vert/pve/cluster:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ShooterGame"
    mem_limit: 16G 
```

## Context
- the `pve` directory is owned by the same PUID and PGID
- the directory is also chmod 777'd
- the only thing that was changed was `acekorneya/asa_server:latest` to `acekorneya/asa_server:2_0_latest`, setting it back to the former makes things go back to normal. its like the latest version doesn't read from the directory or something.
- the server has been running for about 4 months with no issues otherwise
- the servers are running via portainer for the container manager
