### ISSUE TITLE
force_install_dir is not working

### ISSUE THREAD

**Issue by Overactt** [Acekorneya/Ark-Survival-Ascended-Server#81]
Hello, i'm trying to do a ASA server, but i got stuck at some point trying to figure it out for hours now.

I'm creating a contenair in Portainer with the compose : 

```
version: '2.4'

services:
  asaserver:
    image: acekorneya/asa_server:latest
    container_name: asa_Server
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - BATTLEEYE=FALSE  # Set to TRUE to use BattleEye, FALSE to not use BattleEye
      - MAP_NAME=TheIsland
      - SESSION_NAME=xixteur
      - SERVER_ADMIN_PASSWORD=MyPassword
      - ASA_PORT=7777
      - QUERY_PORT=27015
      - MAX_PLAYERS=70
      - CLUSTER_ID=cluster
      - MOD_IDS=          # Add your mod IDs here, separated by commas, e.g., "123456789,987654321"
    ports:
      - "7777:7777/tcp"
      - "7777:7777/udp"
      - "27015:27015/tcp"
      - "27015:27015/udp"
    volumes:
      - "/mnt/server/ark/ASA:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame"
      - "/mnt/server/ark/ARK Survival Ascended Dedicated Server:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server"
      - "/mnt/server/ark/Cluster:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ShooterGame"
    mem_limit: 16G 
```

So. I got a proxmox pool that is mounted into my docker LXC. I got an environnement already running an ARR stacks etc.

So my pool is /zpool/server/ark bind into /mnt/server/ark. I know i got enough space and that he it's mapped good because i have a smb share into mnt/server (screen). 

![Image](https://github.com/user-attachments/assets/bbc18903-cbb7-4ba4-9915-a2205ca1ffdf)

![Image](https://github.com/user-attachments/assets/bc07ca3a-f3a9-4bce-8d07-16994be8fddf)

I check all the perms and it seems good. I don't know what i'm doing wrong. Files are creating into the good spot and stuff. I don't know.

Thanks for the help

![Image](https://github.com/user-attachments/assets/8914e2be-b0a1-45d5-874c-2739ff7a50eb)

[_asa_Server_logs.txt](https://github.com/user-attachments/files/19043879/_asa_Server_logs.txt)
