### ISSUE TITLE
World Progress Reset After Container Rebuild + Unexpected Long Update Time

### ISSUE THREAD

**Issue by Tama47** [Acekorneya/Ark-Survival-Ascended-Server#83]
## Description
I have my entire Docker volume backed up, so I can restore my world to a previous state as needed. This was working correctly before.

But after an update, I had to delete and rebuild the container. All the files were the same as before, but when I loaded into the game, the world had reset to day 1, and my character level was also reset—all progress was lost.

I also noticed some unusual behavior:

- Every time I rebuild the container, it takes **around 40 minutes** for the `Update/Installation in progress, waiting for it to complete...` step.
- It seems to **redownload everything** each time, even though persistent storage is set.
- It seems the container is **not using persistent storage properly** (potential error?), even though no configurations were changed.

## Expected Behavior
- The world and character progress should be preserved after a container rebuild if persistent storage is configured correctly.
- The update process should not take an excessive amount of time or redownload everything if the necessary files are already there.

## Steps to Reproduce
1. Backup the Docker volume.
2. Delete and rebuild the container.
3. Start the container and check if world progress is saved.
4. See the long update time and whether the container redownloads everything.

## Additional Information
- **Docker Setup:** Synology Container Manager version 24.0.2-1535, Docker Compose .yaml file.
- **Full Logs:** [Ark-Server.html.txt](https://github.com/user-attachments/files/19146223/Ark-Server.html.txt) (remove .txt, can be view in browser)

```
version: '2.4'

services:
  asaserver:
    build: .
    image: acekorneya/asa_server:2_0_latest
    container_name: Ark-Server
    restart: unless-stopped
    environment:
      - INSTANCE_NAME=Ark-Survival-Ascended
      - TZ=America/Los_Angeles
      - BATTLEEYE=FALSE
      - RCON_ENABLED=TRUE
      - DISPLAY_POK_MONITOR_MESSAGE=FALSE
      - UPDATE_SERVER=TRUE
      - CHECK_FOR_UPDATE_INTERVAL=24
      - UPDATE_WINDOW_MINIMUM_TIME=12:00 AM
      - UPDATE_WINDOW_MAXIMUM_TIME=11:59 PM
      - RESTART_NOTICE_MINUTES=30
      - ENABLE_MOTD=FALSE
      - MOTD=
      - MOTD_DURATION=30
      - MAP_NAME=TheCenter_WP
      - SESSION_NAME=[REDACTED]
      - SERVER_ADMIN_PASSWORD=[REDACTED]
      - SERVER_PASSWORD=
      - ASA_PORT=7777
      - RCON_PORT=27020
      - MAX_PLAYERS=10
      - SHOW_ADMIN_COMMANDS_IN_CHAT=FALSE
      - CLUSTER_ID=
      - MOD_IDS=
      - PASSIVE_MODS=
      - CUSTOM_SERVER_ARGS=
    ports:
      - "7777:7777/tcp"
      - "7777:7777/udp"
      - "27020:27020/tcp"
    volumes:
      - "/volume1/docker/ark-server/ServerFiles/arkserver:/home/pok/arkserver"
      - "/volume1/docker/ark-server/Instance/Saved:/home/pok/arkserver/ShooterGame/Saved"
      - "/volume1/docker/ark-server/Cluster:/home/pok/arkserver/ShooterGame/Saved/clusters"
    mem_limit: 16G
```
Error:
![Image](https://github.com/user-attachments/assets/fa5a0285-a66b-43df-b91c-c97bf79dcc7c)
Update/Installation in progress everytime I rebuild the container.
<img width="1050" alt="Image" src="https://github.com/user-attachments/assets/64733ce0-e991-4750-b7f6-d84294a9f65a" />

**Comment by Acekorneya** [comment]
well i see some issues with your docker-compose file did you change it as the container name, the instance name and in your volume the instance name dont match at all which could cause a lot of issues with save files etc.. did you use the -create function when creating an instance and if you did a long time a go can you do ne again and see what it creates and should give me an idea was going on.. like here is an example of how one should look like:
```yaml
version: '2.4'

services:
  asaserver:
    build: .
    image: acekorneya/asa_server:2_1_latest
    container_name: asa_PVE_Scorched 
    restart: unless-stopped
    environment:
      - INSTANCE_NAME=PVE_Scorched
      - API=FALSE
      - TZ=America/Los_Angeles
      - BATTLEEYE=TRUE
      - RCON_ENABLED=TRUE
      - DISPLAY_POK_MONITOR_MESSAGE=FALSE
      - UPDATE_SERVER=TRUE
      - CHECK_FOR_UPDATE_INTERVAL=1
      - UPDATE_WINDOW_MINIMUM_TIME=4:00 AM
      - UPDATE_WINDOW_MAXIMUM_TIME=6:00 AM
      - RESTART_NOTICE_MINUTES=30
      - ENABLE_MOTD=TRUE
      - MOTD=<RichColor Color="0.65, 0, 1 ,1">Welcom To Our POK Server</> \n <RichColor Color="1, 1, 0, 1">Official Server Rates for Taming/Harvest/Maturation/Hatch/XP/Imprint</> \n <RichColor Color="1, 0, 0, 1">Join Our Discord discord.gg/9GJKWjQuXy For Server Updates</> \n <RichColor Color="1, 1, 0, 1">No Cryopod Restrictions</>
      - MOTD_DURATION=40
      - MAP_NAME=ScorchedEarth
      - SESSION_NAME=POK-Community-CrossARK-Scorched-NO-WIPE
      - SERVER_ADMIN_PASSWORD=ace
      - SERVER_PASSWORD=
      - ASA_PORT=8777
      - RCON_PORT=27021
      - MAX_PLAYERS=70
      - SHOW_ADMIN_COMMANDS_IN_CHAT=TRUE
      - CLUSTER_ID=kny512
      - MOD_IDS=946694,924900,934749,983782
      - PASSIVE_MODS=
      - CUSTOM_SERVER_ARGS=-UseDynamicConfig
    ports:
      - "8777:8777/tcp"
      - "8777:8777/udp"
      - "27021:27021/tcp"
    volumes:
      - "/home/factorioserver/ASA_Server/ServerFiles/arkserver:/home/pok/arkserver"
      - "/home/factorioserver/ASA_Server/Instance_PVE_Scorched/Saved:/home/pok/arkserver/ShooterGame/Saved"
      - "/home/factorioserver/ASA_Server/Cluster:/home/pok/arkserver/ShooterGame/Saved/clusters"
    mem_limit: 18G
```

**Comment by Tama47** [comment]
Thanks for the response! I restored the files from a backup and I've changed the instance name as well as the volume path. Everything seems to be running okay now. I have only one container running Ark, so I didn't create it with a specific map names or anything. Is just changing the instance name and the instance volume sufficient, if I wanted to play a new map?
```
version: '2.4'

services:
  asaserver:
    build: .
    image: acekorneya/asa_server:2_0_latest
    container_name: Ark-Server
    restart: unless-stopped
    environment:
      - INSTANCE_NAME=TheCenter_WP
      - TZ=America/Los_Angeles
      - BATTLEEYE=FALSE
      - RCON_ENABLED=TRUE
      - DISPLAY_POK_MONITOR_MESSAGE=FALSE
      - UPDATE_SERVER=TRUE
      - CHECK_FOR_UPDATE_INTERVAL=24
      - UPDATE_WINDOW_MINIMUM_TIME=12:00 AM
      - UPDATE_WINDOW_MAXIMUM_TIME=11:59 PM
      - RESTART_NOTICE_MINUTES=30
      - ENABLE_MOTD=FALSE
      - MOTD=
      - MOTD_DURATION=30
      - MAP_NAME=TheCenter_WP
      - SESSION_NAME=[REDACTED]
      - SERVER_ADMIN_PASSWORD=[REDACTED]
      - SERVER_PASSWORD=
      - ASA_PORT=7777
      - RCON_PORT=27020
      - MAX_PLAYERS=10
      - SHOW_ADMIN_COMMANDS_IN_CHAT=FALSE
      - CLUSTER_ID=
      - MOD_IDS=
      - PASSIVE_MODS=
      - CUSTOM_SERVER_ARGS=
    ports:
      - "7777:7777/tcp"
      - "7777:7777/udp"
      - "27020:27020/tcp"
    volumes:
      - "/volume1/docker/ark-server/ServerFiles/arkserver:/home/pok/arkserver"
      - "/volume1/docker/ark-server/Instance_TheCenter_WP/Saved:/home/pok/arkserver/ShooterGame/Saved"
      - "/volume1/docker/ark-server/Cluster:/home/pok/arkserver/ShooterGame/Saved/clusters"
    mem_limit: 16G
```
