### ISSUE TITLE
My configs inside of my instances keep getting overwritten

### ISSUE THREAD

**Issue by zogarr** [Acekorneya/Ark-Survival-Ascended-Server#98]
I have been trying to migrate a server over to a VPS - but my servers continue to get overwritten.

I noticed some other people had the same issue - but it appears it was -UseDynamicConfig - but I can't find that anywhere.

Any ideas would be awesome.

I checked the Docker Config - and my - "CUSTOM_SERVER_ARGS = " was empty.

Here is the command line
[2025.05.02-03.39.16:955][  1]Commandline:  TheIsland_WP?listen?SessionName="MyServer"?RCONEnabled=True?RCONPort=27020?ServerAdminPassword=myadminpassword -Port=7777 -WinLiveMaxPlayers=70 -clusterid=cluster -servergamelog -servergamelogincludetribelogs -ServerRCONOutputTribeLogs -NoBattlEye
And here is the docker file from editing the instance.

```
version: '2.4'

services:
  asaserver:
    build: .
    image: acekorneya/asa_server:2_1_latest
    container_name: asa_test_island
    restart: unless-stopped
    environment:
      - INSTANCE_NAME=test_island
      - TZ=America/Chicago
      - BATTLEEYE=FALSE
      - API=FALSE
      - RCON_ENABLED=TRUE
      - DISPLAY_POK_MONITOR_MESSAGE=FALSE
      - RANDOM_STARTUP_DELAY=TRUE
      - UPDATE_SERVER=TRUE
      - CHECK_FOR_UPDATE_INTERVAL=24
      - UPDATE_WINDOW_MINIMUM_TIME=12:00 AM
      - UPDATE_WINDOW_MAXIMUM_TIME=11:59 PM
      - RESTART_NOTICE_MINUTES=30
      - ENABLE_MOTD=FALSE
      - MOTD=Welcome To my Server
      - MOTD_DURATION=30
      - MAP_NAME=TheIsland_WP
      - SESSION_NAME=MyServer
      - SERVER_ADMIN_PASSWORD=myadminpassword
      - SERVER_PASSWORD=
      - ASA_PORT=7777
      - RCON_PORT=27020
      - MAX_PLAYERS=10
      - SHOW_ADMIN_COMMANDS_IN_CHAT=FALSE
      - CLUSTER_ID=cluster
      - MOD_IDS=
      - PASSIVE_MODS=
    ports:
      - "7777:7777/tcp"
      - "7777:7777/udp"
      - "27020:27020/tcp"
    volumes:
      - "/home/pokuser/ark/ServerFiles/arkserver:/home/pok/arkserver"
      - "/home/pokuser/ark/Instance_test_island/Saved:/home/pok/arkserver/ShooterGame/Saved"
      - "/home/pokuser/ark/Cluster:/home/pok/arkserver/ShooterGame/Saved/clusters"
    mem_limit: 16G
```
I removed CUSTOM_SERVER_ARGs to see if it would make a difference.
